### ISSUE TITLE
Missing main entry in dist folder Version 3.0.2

### ISSUE THREAD

**Issue by rickh18** [n0th1ng-else/webpack-config-dump-plugin#18]
Thank you for updating this package. I noticed that the index .js is missing in the dist folder for version 3.0.2. Looks like the same issue as #14 

`Cannot find module './node_modules/webpack-config-dump-plugin/dist/index.js'. Please verify that the package.json has a valid "main" entry`

Could you verify this and fix the release? 

Thank you!

**Comment by acacha** [comment]
I can confirm this error

**Comment by rickh18** [comment]
@n0th1ng-else are you planning on fixing this? You now published a broken version which breaks my builds.

**Comment by n0th1ng-else** [comment]
hey guys, I do not know ow I missed the notification for this issue and thank you for pinging me here! 

I will take a look soon

**Comment by n0th1ng-else** [comment]
hey @rickh18 @acacha Should be fixed now, could you please try v3.0.3? Thank you for flagging this! Reopening for your feedback

**Comment by rickh18** [comment]
Hi @n0th1ng-else,
Can confirm that v3.0.3 works again. Thank you for creating and maintaining this great plugin!

Rickl

**Comment by n0th1ng-else** [comment]
happy to hear that, Rick! thank you for letting me know
